### PR TITLE
Fix EPNN 

### PR DESCRIPTION
**Pull request by co63oc**
### PR types

Others 
### PR changes

Others 
### Describe

补充文档修改

https://github.com/PaddlePaddle/PaddleScience/pull/606#pullrequestreview-1706130391

### CODE REVIEW

**Comment by lijialin03** [comment]
> wget https://paddle-org.bj.bcebos.com/paddlescience/datasets/dstress-16-plas.dat --output datasets/dstress-16-plas.dat

数据我已上传，在 `https://paddle-org.bj.bcebos.com/paddlescience/datasets/epnn/dstress-16-plas.dat` ，就是在datasets这一级后面加个“epnn”

整体应该是 `wget https://paddle-org.bj.bcebos.com/paddlescience/datasets/epnn/dstate-16-plas.dat -P ./datasets/`

其他的下载数据集命令也需相应改动，谢谢

**Comment by co63oc** [comment]
> > wget https://paddle-org.bj.bcebos.com/paddlescience/datasets/dstress-16-plas.dat --output datasets/dstress-16-plas.dat
> 
> 数据我已上传，在 `https://paddle-org.bj.bcebos.com/paddlescience/datasets/epnn/dstress-16-plas.dat` ，就是在datasets这一级后面加个“epnn”
> 
> 整体应该是 `wget https://paddle-org.bj.bcebos.com/paddlescience/datasets/epnn/dstate-16-plas.dat -P ./datasets/`
> 
> 其他的下载数据集命令也需相应改动，谢谢

已修改

**Comment by lijialin03** [comment]
> -P ./datasets/

**Comment by co63oc** [comment]
已修改

**Review by lijialin03 — APPROVED** [review]

**Review by HydrogenSulfate — APPROVED** [review]
LGTM

**Pull request merged**
