### PR TITLE
Add Transformer-Physx

### PR DESCRIPTION
**Pull request by zhiminzhang0830**
### PR types

New features 
### PR changes

Others 
### Describe

添加Tranaformer-Physx（Transformers for Modeling Physical Systems）算法；

参考代码：https://github.com/zabaras/transformer-physx
论文地址：https://arxiv.org/abs/2010.03957

### CODE REVIEW

**Comment by zhiminzhang0830** [comment]
transformer-physx模型训练：
1. 下载训练数据集
     Lorenz train data: https://drive.google.com/uc?export=download&id=1vGTGzaqEZxxuLN9K-PUrYw9SLWttdDYd
     Lorenz valid data: https://drive.google.com/uc?export=download&id=1bxFzKg8tSagE8kXWGm2mtaJ4gPsKJ8sI
2. 更改以下文件的数据集路径（train_data_path和valid_data_path）：
   examples/lorenz/train_enn.py 
   examples/lorenz/train_transformer.py
3. 训练embedding模型：python examples/lorenz/train_enn.py 
4. 训练transformer模型：python examples/lorenz/train_transformer.py

**Comment by zhiminzhang0830** [comment]
Cylinder 训练数据下载：
    train data：https://drive.google.com/uc?id=1i6ObgR4GsSMRBJ16rdMvexgU2egKYT3v
    valid data: https://drive.google.com/uc?id=10I_uqaKgq82IxTKiRnaJ39Ajpe4e8Rws
Rossler 训练数据下载：
   train data: https://drive.google.com/uc?export=download&id=1eEXYbiZEz5rlEBoF3erDA_sqNWP0AFtp
   valid data: https://drive.google.com/uc?export=download&id=1LSCmkeM2Z6n8f5bzTkx50YuZvcL2WLsk

**Comment by zhiminzhang0830** [comment]
@HydrogenSulfate done

**Review by HydrogenSulfate — APPROVED** [review]
LGTM

**Pull request merged**
